### ISSUE TITLE
Thank you for sharing

### ISSUE THREAD

**Issue by iainelder** [pechorin/sync-repo-docs-to-notion#1]
I searched on Google for `sync markdown to notion` and found your announcement on the [Notion subreddit](https://www.reddit.com/r/Notion/comments/1726gro/github_action_for_sync_repository_markdown_files/).

Thanks for sharing your work. I'm looking forward to try this solution. Others I've tried didn't work well for me.

Does it work outside of a GitHub action?

**Comment by pechorin** [comment]
Hello, thank you for response! Sorry for delayed answer. I think maybe you already find solution. 

index.js is not dependent on any github api, it just looks for markdown files inside folder `process.env.FOLDER` and then exports them to notion.

```
const REQUIRED_ENV_VARS = ['FOLDER', 'NOTION_TOKEN', 'NOTION_ROOT_PAGE_ID', 'RELATIVE_URLS_ROOT']
```

**Comment by iainelder** [comment]
Thanks @pechorin . I don't need to sync to Notion any more, so I'll close this.
